language: node_js
node_js:
- node
branches:
  only:
  - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
    - chaos@xuyuanxiang.cn
    on_success: never
    on_failure: always
before_deploy: npm run build
after_deploy: npm run coveralls
deploy:
  on:
    tags: true
  provider: npm
  email: chaos@xuyuanxiang.cn
  api_key:
    secure: UQ1QgyXpogn5yszKfz3Di19hEAJGOloWav6Bo57uTM3LxxCZBRLc3o9jaNqAW83p0QWjbr/iS4IHRF59wXQi75ExJ1VyhUsMU5Yy52BHVA1AfjKhilO2iP12oyA2oYgyL/zRLYVAYNhpPPl/J0/kPVAF0dYDHVvSvoSHE5cl3R1c5+jjKhdKLT9/RRTiHgasvrol1nEvYcF8L1x1VCbdrvtNlgMiRcRADatO5kx5gFofCVfPKQCI/ZnOacoT9YvRY3fKPSefOLNZbdVHiakYebOcO3F77ZbKiBbG0deOpdW099Uhf/sCLP5UO4eUYddZknoW4MtkBhxC8pOiz4SUH8E9dM+8zlvpQoPtsVpWHMO5taqnm/xJEeHFD/eoJ5x9or0d7MMfoHX+SaaV6N6n7q6LF6QSgXuBTm89Kk9LC+rMJ06GeXKuoWIXp8VGVcifz0FB/azkw+h8Ia13BQeEEdu8DzCV0pd2S6zDYrEQZ2sHVJzeWAXAt7VKjxV+NvV+n4D+rIDuSfBixa4v221vgvQ7V08oCjzwYYhq46fkQ4jrAnb+V0NiqlcI2ezuG77MElOtGT83Tfuz5ERGOy0YmSiMtz0eGP2Z+rFoydP6uem9SivwxW9gZxYD/QzNDseRxWpilfpqu2OmqzEVeiwUe0qxLoHiOvP5Ovi9CETlZyo=
