language: node_js
node_js:
  - node
branches:
  only:
    - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
      - chaos@xuyuanxiang.cn
    on_success: never
    on_failure: always
before_deploy: npm run build
after_deploy: npm run coveralls
deploy:
  on:
    tags: true
  provider: npm
  email: chaos@xuyuanxiang.cn
  api_key:
    secure: KeYg+Jq0hfdW3CWIhQS31nLHuFJOrc3BLJhVSMDqFhkPsb6Q9b5/22LPEyZXfGIq8qIEaFWbIREotXfSISwbkyve0gW+1tbSuwOC2+ETIrQ0rQaGQEUc9U1ppdXqCvW/Ci1zKdB+wCKJr90U2gCQRHQOoa3I2ltCL47sNj9jKUvfI7vD3QlGnoUhvA3OzYexRr7DDNapbCVbvRr5F/FrrWd3/7NYFvAhSJ8UVl8n8iajhiZ3+FY68ll8UEuHKulPhGwxCDSytBISZik6C/B8rPJCARxl9NQf5cZKRU34i4zjfMRxKH+NAKNWmegUQjJhJE4LzhhTaNcKI80+mETbyiRv7GHHpsh9z3m1HA5fy6yGNRxuV4Kplh9ONedSmNSCCjX9QEiJIhCt3xqpEcyCAUaHDD42bg5oIYwGvhOLV8HCksMDnj4VGsovTwnBwg90u1RXIWGv/6OFV36oDekamYmdt8gsgL7BFaT9dPPPZRqxKN0wXfWybpoMmn7Df/zhXKMXCEZrbxTaw1tenKI6hUoZRC4c8jq9XXbwAmPcFHp2noZDSvpPbmh8kxUqczcGqmeCET93EQ7kS+DQkYKpVw84I2gIlqGS86FVV0QApKufmD2AcaKCNcNhxb5GDC8LlIwoDGk1YxP/qw3+3mSBpDvC8lcN/D3vfB+8qEM/v7k=
